@echo off
echo Deploying Final Production Build...
git add src/App.tsx src/components/layout/Header.tsx src/components/layout/Footer.tsx src/data/blogPosts.ts src/pages/blog/BlogPage.tsx src/pages/blog/BlogPost.tsx src/store/authStore.ts src/pages/portal/SignupPage.tsx src/pages/portal/LoginPage.tsx src/pages/portal/ChatPage.tsx
echo Committing...
git commit -m "Complete Blog section and Portal Signup with Discount logic"
echo Pushing...
git push origin main
echo Done.
