@echo off
echo Restoring robust Vercel configuration...
git add vercel.json
echo Committing...
git commit -m "Restore full Vercel config to fix black screen"
echo Pushing...
git push origin main
echo Done.
