@echo off
echo Deploying Cart functionality and Pricing updates...
git add src/store/cartStore.ts src/data/products.ts src/components/cart/CartDrawer.tsx src/components/layout/MainLayout.tsx src/pages/pricing/PricingPage.tsx src/pages/checkout/CheckoutPage.tsx
echo Committing...
git commit -m "Implement full Shopping Cart functionality, increase pricing, and streamline checkout"
echo Pushing...
git push origin main
echo Done.
