@echo off
echo Deploying Pricing and Checkout enhancements...
git add src/data/products.ts src/pages/pricing/PricingPage.tsx src/pages/checkout/CheckoutPage.tsx
echo Committing...
git commit -m "Enhance Pricing and Checkout: Add individual agents, shared data, and renewal date logic"
echo Pushing...
git push origin main
echo Done.
