@echo off
echo Deploying Phase 1: Critical Bugs & Core Enhancements...
git add src/App.tsx src/components/ScrollToTop.tsx src/store/cartStore.ts src/components/cart/CartDrawer.tsx src/components/layout/Header.tsx src/components/chat/ChatWidget.tsx src/data/products.ts src/pages/pricing/PricingPage.tsx src/components/layout/Footer.tsx src/pages/landing/LandingPage.tsx
echo Committing...
git commit -m "Fix critical bugs (scroll, cart, mobile) and add new packages/ROI"
echo Pushing...
git push origin main
echo Done.
