@echo off
echo Deploying Final Fixes (Logo & Case Studies)...
git add src/components/layout/Header.tsx src/pages/casestudies/CaseStudiesPage.tsx src/App.tsx
echo Committing...
git commit -m "Restore logo and add Case Studies page"
echo Pushing...
git push origin main
echo Done.
