@echo off
echo Force adding all changes...
git add .
echo Committing...
git commit -m "Force commit all changes including CSS cleanup and pricing fixes"
echo Pushing...
git push origin main
echo Done.
