@echo off
echo Removing temporary style hacks from index.html...
git add index.html
echo Committing...
git commit -m "Clean up index.html: Remove temporary visibility hacks"
echo Pushing...
git push origin main
echo Done.
