@echo off
echo Removing aggressive CSS overrides...
git add src/styles/text-fix.css
echo Committing...
git commit -m "Remove aggressive CSS overrides to fix layout issues"
echo Pushing...
git push origin main
echo Done.
