@echo off
echo Updating Pricing Page link...
git add src/pages/pricing/PricingPage.tsx
echo Committing...
git commit -m "Update Pricing Page to link to dynamic checkout"
echo Pushing...
git push origin main
echo Done.
