@echo off
echo Fixing missing dependency: @radix-ui/react-slot...
git add package.json
echo Committing...
git commit -m "Fix build error: Add @radix-ui/react-slot to dependencies"
echo Pushing...
git push origin main
echo Done.
