@echo off
echo Fixing missing dependency: zustand...
git add package.json
echo Committing...
git commit -m "Fix build error: Add zustand to dependencies"
echo Pushing...
git push origin main
echo Done.
