@echo off
echo Adding Error Boundary for debugging...
git add src/components/ErrorBoundary.tsx src/main.tsx
echo Committing...
git commit -m "Add Error Boundary to catch runtime errors causing black screen"
echo Pushing...
git push origin main
echo Done.
