@echo off
echo Setting remote...
git remote set-url origin https://github.com/CC90210/oasis-ai-platform.git
echo Adding files...
git add .
echo Committing...
git commit -m "Fix Vercel build error: Add @vercel/node and update package.json"
echo Pushing...
git push origin main
echo Done.
