@echo off
echo Fixing Vite build configuration...
git add vite.config.ts
echo Committing...
git commit -m "Fix critical build issue: Use stable hashing instead of Date.now()"
echo Pushing...
git push origin main
echo Done.
