@echo off
echo Fixing ReferenceError: Target is not defined...
git add src/pages/landing/LandingPage.tsx
echo Committing...
git commit -m "Fix ReferenceError: Import missing Target icon in LandingPage"
echo Pushing...
git push origin main
echo Done.
