@echo off
echo Adding updated checkout and agent pages...
git add src/pages/checkout/CheckoutPage.tsx src/pages/services/AgentPage.tsx
echo Committing...
git commit -m "Implement dynamic pricing and agent selection in checkout"
echo Pushing...
git push origin main
echo Done.
