@echo off
echo Fixing missing dependencies: tailwindcss-animate...
git add package.json
echo Committing...
git commit -m "Fix build error: Add tailwindcss-animate and utils to dependencies"
echo Pushing...
git push origin main
echo Done.
