@echo off
echo Adding updated package.json...
git add package.json
echo Committing...
git commit -m "Move @vercel/node to dependencies to fix build error"
echo Pushing...
git push origin main
echo Done.
