@echo off
echo Installing dependencies...
npm install
echo Adding files...
git add package.json package-lock.json src/pages/checkout/CheckoutPage.tsx
echo Committing...
git commit -m "Implement PayPal integration and update checkout flow"
echo Pushing...
git push origin main
echo Done.
