@echo off
echo Installing dependencies...
npm install
echo Adding package-lock.json...
git add package-lock.json
echo Committing...
git commit -m "Update package-lock.json with @vercel/node"
echo Pushing...
git push origin main
echo Done.
